/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as NegociosRouteImport } from './routes/negocios'
import { Route as DigitalRouteImport } from './routes/digital'
import { Route as DepartamentosRouteImport } from './routes/departamentos'
import { Route as AvisoDeAfiliadosRouteImport } from './routes/aviso-de-afiliados'
import { Route as AchadosRouteImport } from './routes/achados'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociosRoute = NegociosRouteImport.update({
  id: '/negocios',
  path: '/negocios',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalRoute = DigitalRouteImport.update({
  id: '/digital',
  path: '/digital',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartamentosRoute = DepartamentosRouteImport.update({
  id: '/departamentos',
  path: '/departamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDeAfiliadosRoute = AvisoDeAfiliadosRouteImport.update({
  id: '/aviso-de-afiliados',
  path: '/aviso-de-afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const AchadosRoute = AchadosRouteImport.update({
  id: '/achados',
  path: '/achados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achados': typeof AchadosRoute
  '/aviso-de-afiliados': typeof AvisoDeAfiliadosRoute
  '/departamentos': typeof DepartamentosRoute
  '/digital': typeof DigitalRoute
  '/negocios': typeof NegociosRoute
  '/ofertas': typeof OfertasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achados': typeof AchadosRoute
  '/aviso-de-afiliados': typeof AvisoDeAfiliadosRoute
  '/departamentos': typeof DepartamentosRoute
  '/digital': typeof DigitalRoute
  '/negocios': typeof NegociosRoute
  '/ofertas': typeof OfertasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achados': typeof AchadosRoute
  '/aviso-de-afiliados': typeof AvisoDeAfiliadosRoute
  '/departamentos': typeof DepartamentosRoute
  '/digital': typeof DigitalRoute
  '/negocios': typeof NegociosRoute
  '/ofertas': typeof OfertasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achados'
    | '/aviso-de-afiliados'
    | '/departamentos'
    | '/digital'
    | '/negocios'
    | '/ofertas'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/suporte'
    | '/termos'
    | '/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achados'
    | '/aviso-de-afiliados'
    | '/departamentos'
    | '/digital'
    | '/negocios'
    | '/ofertas'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/suporte'
    | '/termos'
    | '/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/achados'
    | '/aviso-de-afiliados'
    | '/departamentos'
    | '/digital'
    | '/negocios'
    | '/ofertas'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/suporte'
    | '/termos'
    | '/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchadosRoute: typeof AchadosRoute
  AvisoDeAfiliadosRoute: typeof AvisoDeAfiliadosRoute
  DepartamentosRoute: typeof DepartamentosRoute
  DigitalRoute: typeof DigitalRoute
  NegociosRoute: typeof NegociosRoute
  OfertasRoute: typeof OfertasRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SobreRoute: typeof SobreRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocios': {
      id: '/negocios'
      path: '/negocios'
      fullPath: '/negocios'
      preLoaderRoute: typeof NegociosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital': {
      id: '/digital'
      path: '/digital'
      fullPath: '/digital'
      preLoaderRoute: typeof DigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departamentos': {
      id: '/departamentos'
      path: '/departamentos'
      fullPath: '/departamentos'
      preLoaderRoute: typeof DepartamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-afiliados': {
      id: '/aviso-de-afiliados'
      path: '/aviso-de-afiliados'
      fullPath: '/aviso-de-afiliados'
      preLoaderRoute: typeof AvisoDeAfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achados': {
      id: '/achados'
      path: '/achados'
      fullPath: '/achados'
      preLoaderRoute: typeof AchadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchadosRoute: AchadosRoute,
  AvisoDeAfiliadosRoute: AvisoDeAfiliadosRoute,
  DepartamentosRoute: DepartamentosRoute,
  DigitalRoute: DigitalRoute,
  NegociosRoute: NegociosRoute,
  OfertasRoute: OfertasRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SobreRoute: SobreRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
