/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendaNaObaRouteImport } from './routes/venda-na-oba'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as NegociosRouteImport } from './routes/negocios'
import { Route as DigitalRouteImport } from './routes/digital'
import { Route as DepartamentosRouteImport } from './routes/departamentos'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AvisoDeAfiliadosRouteImport } from './routes/aviso-de-afiliados'
import { Route as AchadosRouteImport } from './routes/achados'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin.produtos.novo'
import { Route as AdminProdutosIdEditarRouteImport } from './routes/admin.produtos.$id.editar'

const VendaNaObaRoute = VendaNaObaRouteImport.update({
  id: '/venda-na-oba',
  path: '/venda-na-oba',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociosRoute = NegociosRouteImport.update({
  id: '/negocios',
  path: '/negocios',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalRoute = DigitalRouteImport.update({
  id: '/digital',
  path: '/digital',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartamentosRoute = DepartamentosRouteImport.update({
  id: '/departamentos',
  path: '/departamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDeAfiliadosRoute = AvisoDeAfiliadosRouteImport.update({
  id: '/aviso-de-afiliados',
  path: '/aviso-de-afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const AchadosRoute = AchadosRouteImport.update({
  id: '/achados',
  path: '/achados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/admin/produtos/novo',
  path: '/admin/produtos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosIdEditarRoute = AdminProdutosIdEditarRouteImport.update({
  id: '/admin/produtos/$id/editar',
  path: '/admin/produtos/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achados': typeof AchadosRoute
  '/aviso-de-afiliados': typeof AvisoDeAfiliadosRoute
  '/busca': typeof BuscaRoute
  '/departamentos': typeof DepartamentosRoute
  '/digital': typeof DigitalRoute
  '/negocios': typeof NegociosRoute
  '/ofertas': typeof OfertasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/venda-na-oba': typeof VendaNaObaRoute
  '/admin/login': typeof AdminLoginRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/$id/editar': typeof AdminProdutosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achados': typeof AchadosRoute
  '/aviso-de-afiliados': typeof AvisoDeAfiliadosRoute
  '/busca': typeof BuscaRoute
  '/departamentos': typeof DepartamentosRoute
  '/digital': typeof DigitalRoute
  '/negocios': typeof NegociosRoute
  '/ofertas': typeof OfertasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/venda-na-oba': typeof VendaNaObaRoute
  '/admin/login': typeof AdminLoginRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/$id/editar': typeof AdminProdutosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achados': typeof AchadosRoute
  '/aviso-de-afiliados': typeof AvisoDeAfiliadosRoute
  '/busca': typeof BuscaRoute
  '/departamentos': typeof DepartamentosRoute
  '/digital': typeof DigitalRoute
  '/negocios': typeof NegociosRoute
  '/ofertas': typeof OfertasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/venda-na-oba': typeof VendaNaObaRoute
  '/admin/login': typeof AdminLoginRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/$id/editar': typeof AdminProdutosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achados'
    | '/aviso-de-afiliados'
    | '/busca'
    | '/departamentos'
    | '/digital'
    | '/negocios'
    | '/ofertas'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/suporte'
    | '/termos'
    | '/venda-na-oba'
    | '/admin/login'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/produtos/novo'
    | '/admin/produtos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achados'
    | '/aviso-de-afiliados'
    | '/busca'
    | '/departamentos'
    | '/digital'
    | '/negocios'
    | '/ofertas'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/suporte'
    | '/termos'
    | '/venda-na-oba'
    | '/admin/login'
    | '/produto/$slug'
    | '/admin'
    | '/admin/produtos/novo'
    | '/admin/produtos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/achados'
    | '/aviso-de-afiliados'
    | '/busca'
    | '/departamentos'
    | '/digital'
    | '/negocios'
    | '/ofertas'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/suporte'
    | '/termos'
    | '/venda-na-oba'
    | '/admin/login'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/produtos/novo'
    | '/admin/produtos/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchadosRoute: typeof AchadosRoute
  AvisoDeAfiliadosRoute: typeof AvisoDeAfiliadosRoute
  BuscaRoute: typeof BuscaRoute
  DepartamentosRoute: typeof DepartamentosRoute
  DigitalRoute: typeof DigitalRoute
  NegociosRoute: typeof NegociosRoute
  OfertasRoute: typeof OfertasRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SobreRoute: typeof SobreRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  VendaNaObaRoute: typeof VendaNaObaRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  AdminProdutosIdEditarRoute: typeof AdminProdutosIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venda-na-oba': {
      id: '/venda-na-oba'
      path: '/venda-na-oba'
      fullPath: '/venda-na-oba'
      preLoaderRoute: typeof VendaNaObaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocios': {
      id: '/negocios'
      path: '/negocios'
      fullPath: '/negocios'
      preLoaderRoute: typeof NegociosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital': {
      id: '/digital'
      path: '/digital'
      fullPath: '/digital'
      preLoaderRoute: typeof DigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departamentos': {
      id: '/departamentos'
      path: '/departamentos'
      fullPath: '/departamentos'
      preLoaderRoute: typeof DepartamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-afiliados': {
      id: '/aviso-de-afiliados'
      path: '/aviso-de-afiliados'
      fullPath: '/aviso-de-afiliados'
      preLoaderRoute: typeof AvisoDeAfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achados': {
      id: '/achados'
      path: '/achados'
      fullPath: '/achados'
      preLoaderRoute: typeof AchadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/admin/produtos/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/$id/editar': {
      id: '/admin/produtos/$id/editar'
      path: '/admin/produtos/$id/editar'
      fullPath: '/admin/produtos/$id/editar'
      preLoaderRoute: typeof AdminProdutosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchadosRoute: AchadosRoute,
  AvisoDeAfiliadosRoute: AvisoDeAfiliadosRoute,
  BuscaRoute: BuscaRoute,
  DepartamentosRoute: DepartamentosRoute,
  DigitalRoute: DigitalRoute,
  NegociosRoute: NegociosRoute,
  OfertasRoute: OfertasRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SobreRoute: SobreRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  VendaNaObaRoute: VendaNaObaRoute,
  AdminLoginRoute: AdminLoginRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  AdminProdutosIdEditarRoute: AdminProdutosIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
